Vagrant.configure("2") do |config|

    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true

    config.vm.define "web1" do |web1|
        web1.vm.box = "ubuntu/focal64"
        web1.vm.hostname = "web1"
        web1.vm.network "forwarded_port", id: "ssh", host: 2278, guest: 22
        web1.vm.network "private_network", ip: "10.10.10.78"

        web1.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
        end
    end

    config.vm.define "web2" do |web2|
        web2.vm.box = "ubuntu/focal64"
        web2.vm.hostname = "web2"
        web2.vm.network "forwarded_port", id: "ssh", host: 2279, guest: 22
        web2.vm.network "private_network", ip: "10.10.10.79"

        web2.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
        end
    end
end